FROM aerostack2_gpu
 
RUN pip3 install  numpy
RUN pip3 install matplotlib
RUN pip3 install scipy
RUN pip3 install utm
RUN pip3 install Django==4.0.4
RUN pip3 install websockets
RUN pip3 install websocket-client
RUN pip3 install channels==3.0.4
RUN pip3 install numpy==1.26
